apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: db
  labels:
    app: postgres
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.2-alpine
          ports:
            - containerPort: 5432
          args:
            - -c
            - ssl=on
            - -c
            - ssl_cert_file=/var/lib/postgresql/certs/server.crt
            - -c
            - ssl_key_file=/var/lib/postgresql/certs/server.key
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: db-name
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            - name: certs
              mountPath: /var/lib/postgresql/certs
      securityContext:
        runAsUser: 1
        runAsGroup: 70
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres
        - name: certs
          secret:
            secretName: short-d.com-tls
            defaultMode: 0600
            items:
              - key: tls.crt
                path: server.crt
              - key: tls.key
                path: server.key
---
apiVersion: v1
kind: Service
metadata:
  namespace: db
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 7400
      targetPort: 5432
  type: LoadBalancer
