apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testing
  name: status-frontend
  labels:
    app: status
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      name: status-frontend
      labels:
        app: status
        tier: frontend
    spec:
      containers:
        - name: status-frontend
          image: shortorg/status-frontend-testing
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: status
      tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  namespace: testing
  name: status-frontend
spec:
  selector:
    app: status
    tier: frontend
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: testing
  name: status-frontend
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
    - hosts:
        - status-testing.short-d.com
      secretName: short-d.com-tls
  rules:
    - host: status-testing.short-d.com
      http:
        paths:
          - backend:
              serviceName: status-frontend
              servicePort: 80
