apiVersion: v1
kind: PersistentVolume
metadata:
  name: short-staging
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s/volumes/short/staging"